packages:
  - packages/kissopen-server
  - packages/kissopen-wire
  - packages/kissopen-server-self-host
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
  - sharp
